services:
  library-migration:
    build:
      context: ./library-backend
      target: migration
      dockerfile: ./Dockerfile
    depends_on:
      library-database:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=library_backend.settings
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
  library-createsuperuser:
    build:
      context: ./library-backend
      target: createsuperuser
      dockerfile: ./Dockerfile
    depends_on:
      library-migration:
        condition: service_completed_successfully
    environment:
      - DJANGO_SETTINGS_MODULE=library_backend.settings
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - NEXT_PUBLIC_FRONTEND_PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
  library-backend:
    container_name: ${NEXT_PUBLIC_BACKEND_HOST}
    build:
      context: ./library-backend
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./library-backend/library_backend:/app/library_backend
    environment:
      - DJANGO_SETTINGS_MODULE=library_backend.settings
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - NEXT_PUBLIC_FRONTEND_PORT=${NEXT_PUBLIC_FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      library-createsuperuser:
        condition: service_completed_successfully
    healthcheck:
      test: >
        sh -c "curl -f http://${NEXT_PUBLIC_BACKEND_HOST}:${NEXT_PUBLIC_BACKEND_PORT}/api/publishing-houses/"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    